version: '3.8'

services:
  mvd_back:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: mvd_back
    networks:
      - reverseproxy-nw
    # ports:
    #   - "8001:8001"
    environment:
      NODE_ENV: production
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      API_TOKEN: ${API_TOKEN}

networks:
  reverseproxy-nw:
    external: true
